-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4XIzr8Hct/jIuxCW
bgXmmZkhGWzPmu8TNh3fFsAWYJegCgYIKoZIzj0DAQehRANCAASNY7MawDBxDrwL
rcB3TwrwT48ujnATGmrV50hS/pFC9qPFVWIhbi2TIsog0lWOeAmsM6iwRyz89E14
G2BRawje
-----END PRIVATE KEY-----